### ISSUE TITLE
Can MiniG (Mini Gmail)  AJAX Webmail work with apache james server?

### ISSUE THREAD

**Issue by topstarnetwork** [linagora/james#40]
Can MiniG (Mini Gmail)  AJAX Webmail work with apache james server?

**Comment by chibenwa** [comment]
MiniG supports IMAP and SMTP so I guess it should work just fine.
I previously used James with two other webmails : RondCube and RainLoop.

**Comment by mbaechler** [comment]
I think there's nothing more to say, I'm closing the ticket.
